name: php-mdbm
on: ["push", "pull_request"]
jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    
    # Run build of the application
    - name: Run build
      run: |
        sudo apt update -qq -y
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends tzdata
        sudo apt install -qq -y openssl libcppunit-dev libreadline7 libreadline-dev valgrind libmodule-install-perl gdb php-dev git
        curl -ss -L -O https://github.com/torden/go-mdbm/raw/master/pkg/ubuntu/mdbm-4.13.0-Bionic_Beaver.deb
        sudo dpkg -i mdbm-4.13.0-Bionic_Beaver.deb
        cd src
        sudo dd of=/etc/ld.so.conf <<EOF
        include /etc/ld.so.conf.d/*.conf
        /usr/local/mdbm/lib64
        /usr/lib/php
        EOF
        sudo ldconfig -v
        phpize
        ./configure --with-php-config=/usr/bin/php-config --with-mdbm=/usr/local/mdbm/
        gcc -v
        g++ -v
