name: php-mdbm
on: ["push", "pull_request"]
jobs:
  build_and_test:
    strategy:
      matrix:
       php: ['5.3','5.4','5.5','5.6','7.0','7.1','7.2','7.3','7.4','8.0','8.1','8.2']
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    
    # Setup PHP
    - name: PHP v${{ matrix.go }} 
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }} 
        tools: phpunit, composer, php-config, phpize

    # Install Dependencies
    - name: Install dependencies
      run: |
        sudo apt update -qq -y
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends tzdata
        sudo apt install -qq -y openssl zlib1g libssl1.1 libcppunit-dev libreadline7  libtinfo5 libstdc++6 libc6 libreadline-dev valgrind libmodule-install-perl gdb build-essential make gcc g++
        curl -ss -L -O https://github.com/torden/go-mdbm/raw/master/pkg/ubuntu/mdbm-4.13.0-Bionic_Beaver.deb
        sudo dpkg -i mdbm-4.13.0-Bionic_Beaver.deb

    # Run build of the application
    - name: Run build and Tests
      run: |
        cd src
        sudo dd of=/etc/ld.so.conf <<EOF
        include /etc/ld.so.conf.d/*.conf
        /usr/local/mdbm/lib64
        /usr/lib/php
        EOF
        sudo ldconfig
        php -v
        phpize
        ./configure --with-php-config=`which php-config` --with-mdbm=/usr/local/mdbm/
        make
        # make test TESTS="-q -v -m"
        make test TESTS="-q -v"
